[IMPLEMENT] Migrated to null safety
sbis04/video_trimmer pull request #90
Opened 2021-03-08 15:54 UTC by Jartz

2021-03-10 13:27 UTC, Jartz commented
@sbis04

2021-03-11 04:27 UTC, sbis04 requested changes
Please address the the following comments. 

Though I said that we should delay migrating the package to null safety in order to get **sound null-safety** (as two of the packages on which `video_trimmer` is dependent hasn't yet released their null-safety versions), but using other packages having higher versions with null-safety can result in version solving being failed. 

And if they contain breaking changes, then I think dependency overriding also might fail.

Ref: #92

2021-03-11 04:27 UTC, sbis04 commented on example/ios/Podfile
> +platform :ios, '11.0'
The example project was using the LTS release. As per the [flutter_ffmpeg](https://pub.dev/packages/flutter_ffmpeg) package:

Main releases:
```
platform :ios, '11.0'
```
LTS releases:
```
platform :ios, '9.3'
```

So, the ios deployment target `9.3` should work fine.

2021-04-10 05:26 UTC, sbis04 commented
Have migrated the package to null safety, thanks for the contribution!

2021-04-10 05:26 UTC, closed without merging